- clean:
    - '~'

- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.zshrc:
    ~/.zsh:
    ~/.zshenv:
    ~/.vim:
    ~/.tmux.conf:
    ~/.Xresources:
    ~/.xinitrc:
    ~/.zprofile:
    ~/.cache/wal: wal
    ~/.config/bat: bat
    ~/.config/bspwm: bspwm
    ~/.config/dunst: dunst
    ~/.config/polybar: polybar
    ~/.config/redshift: redshift
    ~/.config/rofi: rofi
    ~/.config/sxhkd: sxhkd

- shell:
    - command: git submodule update --init --recursive
      description: Installing submodules

    - command: source zshrc
      description: Sourcing zshrc
    
    - command: bat cache --build
      description: Built bat cache
