- clean:
    - '~'

- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.zshrc:
    ~/.zsh:
    ~/.zshenv:
    ~/.vim:
    ~/.tmux.conf:
    ~/.xinitrc:
    ~/.Xresources:
    ~/.xsession:
    ~/.cache/wal: wal
    ~/.config/bat: bat
    ~/.config/dunst: dunst
    ~/.config/i3: i3
    ~/.config/polybar: polybar
    ~/.config/redshift: redshift
    ~/.config/rofi: rofi

- shell:
    - command: git submodule update --init --recursive
      description: Installing submodules

    - command: source zshrc
      description: Sourcing zshrc
    
    - command: bat cache --build
      description: Built bat cache
