- clean:
    - '~'

- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.zshrc:
    ~/.zsh:
    ~/.zshenv:
    ~/.vim:
    ~/.tmux.conf:

- shell:
    - command: git submodule update --init --recursive
      description: Installing submodules

    - command: source zshrc
      description: Sourcing zshrc
