- clean:
    - '~'

- defaults:
    link:
      create: true

- link:
    ~/.gitconfig:
    ~/.gittemplate:
    ~/.zshrc:
    ~/.zsh:

- shell:
    - git submodule update --init --recursive
    - which brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - which imagesnap || brew install imagesnap
    - ./zsh/fzf/install --no-fish --no-bash --key-bindings --completion --no-update-rc
    - source zshrc
