- clean:
    - '~'

- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.gitconfig:
    ~/.gittemplate:
    ~/.zshrc:
    ~/.zsh:
    ~/.nvm:
    ~/.iterm2_shell_integration.zsh:
    ~/.vimrc:

- shell:
    - git submodule update --init --recursive
    - which brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - which realpath || brew install coreutils
    - which imagesnap || brew install imagesnap
    - ./zsh/fzf/install --no-fish --no-bash --key-bindings --completion --no-update-rc
    - source zshrc
    - PREFIX=$HOME make -C ./zsh/fasd install

    # iTerm2 settings
    - defaults write com.googlecode.iterm2 PrefsCustomFolder -string $(pwd)/iterm2
    - defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
    - defaults read com.googlecode.iterm2
