#!/bin/sh

function start_sxhkd() {
    killall -q sxhkd
    sxhkd
}

function start_redshift() {
    killall -q redshift
    redshift
}

function start_picom() {
    killall -q picom
    while pgrep -u $UID -x picom >/dev/null; do sleep .5; done
    picom --experimental-backends
}

source "${HOME}/.cache/wal/colors.sh"

start_sxhkd &
start_redshift &
start_picom &

xprop -root -f _NET_DESKTOP_LAYOUT 32cccc -set _NET_DESKTOP_LAYOUT 1,3,3,0
bspc monitor -d $(seq 9)

bspc config window_gap          16
bspc config bottom_padding	36

bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config normal_border_color "$color8"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color13"

bspc rule --add \* state=floating
bspc rule --add kitty state=pseudo_tiled

