#!/bin/sh

function start_polybar() {
    killall -q polybar
    while pgrep -u $UID -x polybar >/dev/null; do sleep .5; done
    polybar top
}

function start_sxhkd() {
    killall -q sxhkd
    sxhkd
}

function start_feh() {
    killall -q feh
    feh --bg-fill --no-fehbg ~/Pictures/Wallpapers/punch-bowl-falls.jpg
}

function start_picom() {
    killall -q picom
    picom --experimental-backends
}

function start_dunst() {
    killall -q dunst
    dunst
}

function start_redshift() {
    killall -q redshift
    while pgrep -u $UID -x redshift >/dev/null; do sleep .5; done
    redshift
}

function start_xsslock() {
    killall -q xss-lock
    xss-lock -- betterlockscreen --lock
}

function start_flameshot() {
    killall -q flameshot
    flameshot
}

function autostart() {
    pgrep firefox || (bspc rule --add firefox desktop=^1 follow=off --one-shot; firefox &)
    pgrep slack || slack &
    pgrep signal-desktop || signal-desktop --start-in-tray &
    pgrep spotify || spotify &
}

source "${HOME}/.cache/wal/colors.sh"

start_sxhkd &
start_picom &
start_feh &
start_polybar &
start_dunst &
start_redshift &
start_xsslock &
start_flameshot &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config normal_border_color "$color8"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color13"

bspc rule --add \* state=floating
bspc rule --add Code desktop=^2
bspc rule --add Slack desktop=^4
bspc rule --add Signal desktop=^4
bspc rule --add Spotify desktop=^5
bspc rule --add Thunderbird desktop=^6
bspc rule --add kitty state=pseudo_tiled

autostart
