# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 3

transient_prompt:
  template: "❯ "
  foreground: "#B48EAD"
  foreground_templates:
    - "{{ if gt .Code 0 }}#BF616A{{ end }}"

console_title_template: "{{ if .Root }}(root) {{ end }}{{ .PWD }}"

final_space: true

secondary_prompt:
  template: "\t"

blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - properties:
          style: full
        template: "{{ .Path }} "
        foreground: "#81A1C1"
        type: path
        style: plain

      - properties:
          branch_ahead_icon: "<#88C0D0>⇡ </>"
          branch_behind_icon: "<#88C0D0>⇣ </>"
          branch_icon: ""
          commit_icon: "@"
          fetch_status: true
          fetch_upstream_icon: true
          github_icon: ""
          mapped_branches:
            feat/*: "🚀/"
            bug/*: "🐛/"
            chore/*: "🧹/"
            hotfix/*: "🔥/"
        template: "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<#FFAFD7>*</>{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }} "
        foreground: "#6C6C6C"
        type: git
        style: plain

      - properties:
          style: austin
          threshold: 5000
        template: " {{ .FormattedMs }} "
        foreground: "#A3BE8C"
        type: executiontime
        style: plain

  - type: prompt
    alignment: left
    newline: true
    segments:
      - properties:
          always_enabled: true
        template: "{{ if .Root }}{{ else }}❯{{ end }}"
        foreground: "#B48EAD"
        type: status
        style: plain
        foreground_templates:
          - "{{ if gt .Code 0 }}#BF616A{{ end }}"

tooltips_action: replace
tooltips:
  - type: aws
    tips:
      - aws
      - sls
      - tf
      - terraform
      - tofu
    template: "  {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"
