#!/bin/sh

function start_polybar() {
    killall -q polybar
    while pgrep -u $UID -x polybar >/dev/null; do sleep .5; done
    polybar top &
}

function start_sxhkd() {
    killall -q sxhkd
    sxhkd &
}

function start_feh() {
    killall -q feh
    feh --bg-fill --no-fehbg ~/Pictures/Wallpapers/arch-mesh.png &
}

function start_compton() {
    killall -q compton
    compton --daemon &
}

function start_dunst() {
    killall -q dunst
    dunst &
}

start_sxhkd
start_compton
start_feh
start_polybar
start_dunst

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#959dcb"

bspc rule --add Firefox desktop=^1 state=floating
bspc rule --add code-oss desktop=^2
bspc rule --add Slack desktop=^4 state=floating
bspc rule --add Signal desktop=^4 state=floating
# bspc rule --add Spotify desktop=^5 state=floating
bspc rule --add Thunderbird desktop=^6
